// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Login: typeof import('./src/components/login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabhead: typeof import('./src/components/tabhead.vue')['default']
    TabHead: typeof import('./src/components/tabHead.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanSearch: typeof import('vant/es')['Search']
  }
}
